### PR TITLE
Use StaticFileHandler instead of ResourceHandler

### PR DESCRIPTION
**Pull request by nashe**
This custom handler was not necessary,  [`StaticFileHandler`](http://www.tornadoweb.org/en/stable/web.html#tornado.web.StaticFileHandler) is already doing the job and is built-in in _Tornado_.

### CODE REVIEW

**Comment by derogab** [comment]
I'll check it out as soon as I can.

**Comment by derogab** [comment]
What is the advantage of using StaticFileHandler instead of ResourceHandler?

**Comment by nashe** [comment]
It's a built-in component, tested and supporting more stuff than `ResourceHandler` do (cache, range, etc). No need to reimplement it.

P.S.: I think we can also use it to remove the `MainHandler` (cf. [the documentation](http://www.tornadoweb.org/en/stable/_modules/tornado/web.html#StaticFileHandler)).

**Comment by derogab** [comment]
Good.

I'm going to merge it.

**Pull request merged**
